/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.rootcheck;

import com.scottyab.rootbeer.RootBeer;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;

@Kroll.module(name = "TiRootCheck", id = "ti.rootcheck")
public class TiRootCheckModule extends KrollModule {

    // Properties

    @Kroll.getProperty
    public Boolean isRooted() {
        RootBeer rootBeer = new RootBeer(TiApplication.getAppCurrentActivity());
        return rootBeer.isRooted();
    }
}
